/*
 *  This file is part of the EPICS QT Framework, initially developed at the Australian Synchrotron.
 *
 *  The EPICS QT Framework is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  The EPICS QT Framework is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with the EPICS QT Framework.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Copyright (c) 2009, 2010 Australian Synchrotron
 *
 *  Author:
 *    Andrew Rhyder
 *  Contact details:
 *    andrew.rhyder@synchrotron.org.au
 */
 
// Packages CA callback data as a Qt event

#ifndef QCAEVENTUPDATE_H
#define QCAEVENTUPDATE_H

#include <QtDebug>
#include <QEvent>
#include <QVariant>

namespace qcaobject { class QCaObject; }

class QCaEventUpdate;

// Simple container for a list QCaEventUpdate instances.
// This class is simply a reference to an update event (an instance of class QCaEventUpdate)
// This class exists so that a list of references to outstanding events can be maintained.
class QCaEventItem {
  public:
    QCaEventItem() {}
    QCaEventItem( QCaEventUpdate *newEvent ) { event = newEvent; }
    QCaEventUpdate *event;
};

// Packages CA callback data as a Qt event
// This class packages data and status generated by a CA callback as a Qt event.
// When data or status updates must be passed from a foreign CA thread to a Qt thread
// an instance of this class is created, populated with the CA information and posted
// through the event mechanism to a Qt thread.
class QCaEventUpdate : public QEvent {
  public:
    QCaEventUpdate( qcaobject::QCaObject *emitterObjectIn,  // The object that emited the event
                    long newReason,                         // Callback reason. Actually of type caobject::callback_reasons
                    void* newDataPtr );                     // CA data. This is actually of type carecord::CaRecord*
    ~QCaEventUpdate();

    static QEvent::Type EVENT_UPDATE_TYPE;
    bool acceptThisEvent;                // If true, the originator of this event has been deleted. Ignore the event.

    qcaobject::QCaObject *emitterObject; // The object to process the data and emit a signal.
    long reason;                         // Callback reason. Actually of type caobject::callback_reasons
    void* dataPtr;                       // CA data. this is actually of type carecord::CaRecord*
};

#endif // QCAEVENTUPDATE_H
